from __future__ import annotations
from pathlib import Path
from typing import List, Tuple
from bashbrush.core.palette import ensure_16, rgb_to_hex
from bashbrush.core.config import update_config
from bashbrush.settings import Paths

def apply_theme(palette: List[Tuple[int,int,int]], wallpaper_path: Path, paths: Paths) -> None:
    print("\n--- Processing foot ---")
    paths.foot_themes.mkdir(parents=True, exist_ok=True)
    normal, brights = ensure_16(palette)

    lines = [
        f"# foot theme generated by bashbrush for {wallpaper_path.name}",
        "[colors]",
        f"background={rgb_to_hex(palette[0], prefix='')}",
        f"foreground={rgb_to_hex(palette[-1], prefix='')}",
        ""
    ]
    for i, c in enumerate(normal):
        lines.append(f"regular{i}={rgb_to_hex(c, prefix='')}")
    for i, c in enumerate(brights):
        lines.append(f"bright{i}={rgb_to_hex(c, prefix='')}")

    theme_filename = wallpaper_path.stem + ".ini"
    theme_path = (paths.foot_themes / theme_filename).resolve()
    theme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Exported foot theme to: {theme_path}")

    update_config(
        paths.foot_config,
        f"include={theme_path}\n",
        r"^\s*include\s*="
    )
