from __future__ import annotations
from pathlib import Path
from typing import List, Tuple
from bashbrush.core.palette import ensure_16, rgb_to_hex
from bashbrush.core.config import update_config
from bashbrush.settings import Paths

def apply_theme(palette: List[Tuple[int,int,int]], wallpaper_path: Path, paths: Paths) -> None:
    print("\n--- Processing Kitty ---")
    paths.kitty_themes.mkdir(parents=True, exist_ok=True)
    normal, brights = ensure_16(palette)

    lines = [
        f"# Kitty theme generated by bashbrush for {wallpaper_path.name}",
        f"background {rgb_to_hex(palette[0])}",
        f"foreground {rgb_to_hex(palette[-1])}",
        f"cursor {rgb_to_hex(palette[-1])}",
        f"selection_background {rgb_to_hex(normal[2])}",
        f"selection_foreground {rgb_to_hex(palette[0])}",
        ""
    ]
    for i, c in enumerate(normal):
        lines.append(f"color{i} {rgb_to_hex(c)}")
    for i, c in enumerate(brights):
        lines.append(f"color{i+8} {rgb_to_hex(c)}")

    theme_filename = wallpaper_path.stem + ".conf"
    theme_path = (paths.kitty_themes / theme_filename).resolve()
    theme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Exported Kitty theme to: {theme_path}")

    update_config(
        paths.kitty_config,
        f"include {theme_path}\n",
        r"^\s*include\s+.*(themes|\.conf)"
    )
